// Column names matching CreateSchema.sql order exactly
const CDR_COLUMNS = [
  "cdrrecordtype",
  "globalcallid_callmanagerid",
  "globalcallid_callid",
  "origlegcallidentifier",
  "datetimeorigination",
  "orignodeid",
  "origspan",
  "origipaddr",
  "callingpartynumber",
  "callingpartyunicodeloginuserid",
  "origcause_location",
  "origcause_value",
  "origprecedencelevel",
  "origmediatransportaddress_ip",
  "origmediatransportaddress_port",
  "origmediacap_payloadcapability",
  "origmediacap_maxframesperpacket",
  "origmediacap_g723bitrate",
  "origvideocap_codec",
  "origvideocap_bandwidth",
  "origvideocap_resolution",
  "origvideotransportaddress_ip",
  "origvideotransportaddress_port",
  "origrsvpaudiostat",
  "origrsvpvideostat",
  "destlegidentifier",
  "destnodeid",
  "destspan",
  "destipaddr",
  "originalcalledpartynumber",
  "finalcalledpartynumber",
  "finalcalledpartyunicodeloginuserid",
  "destcause_location",
  "destcause_value",
  "destprecedencelevel",
  "destmediatransportaddress_ip",
  "destmediatransportaddress_port",
  "destmediacap_payloadcapability",
  "destmediacap_maxframesperpacket",
  "destmediacap_g723bitrate",
  "destvideocap_codec",
  "destvideocap_bandwidth",
  "destvideocap_resolution",
  "destvideotransportaddress_ip",
  "destvideotransportaddress_port",
  "destrsvpaudiostat",
  "destrsvpvideostat",
  "datetimeconnect",
  "datetimedisconnect",
  "lastredirectdn",
  "pkid",
  "originalcalledpartynumberpartition",
  "callingpartynumberpartition",
  "finalcalledpartynumberpartition",
  "lastredirectdnpartition",
  "duration",
  "origdevicename",
  "destdevicename",
  "origcallterminationonbehalfof",
  "destcallterminationonbehalfof",
  "origcalledpartyredirectonbehalfof",
  "lastredirectredirectonbehalfof",
  "origcalledpartyredirectreason",
  "lastredirectredirectreason",
  "destconversationid",
  "globalcallid_clusterid",
  "joinonbehalfof",
  "comment",
  "authcodedescription",
  "authorizationlevel",
  "clientmattercode",
  "origdtmfmethod",
  "destdtmfmethod",
  "callsecuredstatus",
  "origconversationid",
  "origmediacap_bandwidth",
  "destmediacap_bandwidth",
  "authorizationcodevalue",
  "outpulsedcallingpartynumber",
  "outpulsedcalledpartynumber",
  "origipv4v6addr",
  "destipv4v6addr",
  "origvideocap_codec_channel2",
  "origvideocap_bandwidth_channel2",
  "origvideocap_resolution_channel2",
  "origvideotransportaddress_ip_channel2",
  "origvideotransportaddress_port_channel2",
  "origvideochannel_role_channel2",
  "destvideocap_codec_channel2",
  "destvideocap_bandwidth_channel2",
  "destvideocap_resolution_channel2",
  "destvideotransportaddress_ip_channel2",
  "destvideotransportaddress_port_channel2",
  "destvideochannel_role_channel2",
  "incomingprotocolid",
  "incomingprotocolcallref",
  "outgoingprotocolid",
  "outgoingprotocolcallref",
  "currentroutingreason",
  "origroutingreason",
  "lastredirectingroutingreason",
  "huntpilotpartition",
  "huntpilotdn",
  "calledpartypatternusage",
  "incomingicid",
  "incomingorigioi",
  "incomingtermioi",
  "outgoingicid",
  "outgoingorigioi",
  "outgoingtermioi",
  "outpulsedoriginalcalledpartynumber",
  "outpulsedlastredirectingnumber",
  // CUCM 14/15 additional columns
  "wascallqueued",
  "totalwaittimeinqueue",
  "callingpartynumber_uri",
  "originalcalledpartynumber_uri",
  "finalcalledpartynumber_uri",
  "lastredirectdn_uri",
  "mobilecallingpartynumber",
  "finalmobilecalledpartynumber",
  "origmobiledevicename",
  "destmobiledevicename",
  "origmobilecallduration",
  "destmobilecallduration",
  "mobilecalltype",
  "originalcalledpartypattern",
  "finalcalledpartypattern",
  "lastredirectingpartypattern",
  "huntpilotpattern",
  "origdevicetype",
  "destdevicetype",
  "origdevicesessionid",
  "destdevicesessionid",
  // Enrichment columns (populated by AXL lookups)
  "orig_device_description",
  "orig_device_user",
  "orig_device_pool",
  "orig_device_location",
  "dest_device_description",
  "dest_device_user",
  "dest_device_pool",
  "dest_device_location",
  "orig_device_type",
  "orig_device_model",
  "dest_device_type",
  "dest_device_model",
  "calling_party_user",
  "called_party_user",
  "route_pattern_matched",
  "enriched_at",
];

async function insertCdrRecords(pool, records) {
  let inserted = 0;
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    for (const record of records) {
      const placeholders = CDR_COLUMNS.map((_, i) => `$${i + 1}`).join(", ");
      const values = CDR_COLUMNS.map((col) => record[col] ?? null);

      const result = await client.query(
        `INSERT INTO cdr (${CDR_COLUMNS.join(", ")})
         SELECT ${placeholders}
         WHERE NOT EXISTS (SELECT 1 FROM cdr WHERE pkid = $${CDR_COLUMNS.indexOf("pkid") + 1})`,
        values,
      );
      inserted += result.rowCount;
    }
    await client.query("COMMIT");
  } catch (err) {
    await client.query("ROLLBACK");
    throw err;
  } finally {
    client.release();
  }
  return inserted;
}

module.exports = { insertCdrRecords, CDR_COLUMNS };
