INSERT INTO cdr_cause VALUES (0, 'No error');
INSERT INTO cdr_cause VALUES (1, 'Unallocated (unassigned) number');
INSERT INTO cdr_cause VALUES (2, 'No route to specified transit network (national use)');
INSERT INTO cdr_cause VALUES (3, 'No route to destination');
INSERT INTO cdr_cause VALUES (4, 'Send special information tone');
INSERT INTO cdr_cause VALUES (5, 'Misdialed trunk prefix (national use)');
INSERT INTO cdr_cause VALUES (6, 'Channel unacceptable');
INSERT INTO cdr_cause VALUES (7, 'Call awarded and being delivered in an established channel');
INSERT INTO cdr_cause VALUES (8, 'Preemption');
INSERT INTO cdr_cause VALUES (9, 'Preemption-circuit reserved for reuse');
INSERT INTO cdr_cause VALUES (16, 'Normal call clearing');
INSERT INTO cdr_cause VALUES (17, 'User busy');
INSERT INTO cdr_cause VALUES (18, 'No user responding');
INSERT INTO cdr_cause VALUES (19, 'No answer from user (user alerted)');
INSERT INTO cdr_cause VALUES (20, 'Subscriber absent');
INSERT INTO cdr_cause VALUES (21, 'Call rejected');
INSERT INTO cdr_cause VALUES (22, 'Number changed');
INSERT INTO cdr_cause VALUES (26, 'Non-selected user clearing');
INSERT INTO cdr_cause VALUES (27, 'Destination out of order');
INSERT INTO cdr_cause VALUES (28, 'Invalid number format (address incomplete)');
INSERT INTO cdr_cause VALUES (29, 'Facility rejected');
INSERT INTO cdr_cause VALUES (30, 'Response to STATUS ENQUIRY');
INSERT INTO cdr_cause VALUES (31, 'Normal, unspecified');
INSERT INTO cdr_cause VALUES (34, 'No circuit/channel available');
INSERT INTO cdr_cause VALUES (38, 'Network out of order');
INSERT INTO cdr_cause VALUES (39, 'Permanent frame mode connection out of service');
INSERT INTO cdr_cause VALUES (40, 'Permanent frame mode connection operational');
INSERT INTO cdr_cause VALUES (41, 'Temporary failure');
INSERT INTO cdr_cause VALUES (42, 'Switching equipment congestion');
INSERT INTO cdr_cause VALUES (43, 'Access information discarded');
INSERT INTO cdr_cause VALUES (44, 'Requested circuit/channel not available');
INSERT INTO cdr_cause VALUES (46, 'Precedence call blocked');
INSERT INTO cdr_cause VALUES (47, 'Resource unavailable, unspecified');
INSERT INTO cdr_cause VALUES (49, 'Quality of Service not available');
INSERT INTO cdr_cause VALUES (50, 'Requested facility not subscribed');
INSERT INTO cdr_cause VALUES (53, 'Service operation violated');
INSERT INTO cdr_cause VALUES (54, 'Incoming calls barred');
INSERT INTO cdr_cause VALUES (55, 'Incoming calls barred within Closed User Group (CUG)');
INSERT INTO cdr_cause VALUES (57, 'Bearer capability not authorized');
INSERT INTO cdr_cause VALUES (58, 'Bearer capability not presently available');
INSERT INTO cdr_cause VALUES (62, 'Inconsistency in designated outgoing access information and subscriber class');
INSERT INTO cdr_cause VALUES (63, 'Service or option not available, unspecified');
INSERT INTO cdr_cause VALUES (65, 'Bearer capability not implemented');
INSERT INTO cdr_cause VALUES (66, 'Channel type not implemented');
INSERT INTO cdr_cause VALUES (69, 'Requested facility not implemented');
INSERT INTO cdr_cause VALUES (70, 'Only restricted digital information bearer capability is available (national use)');
INSERT INTO cdr_cause VALUES (79, 'Service or option not implemented, unspecified');
INSERT INTO cdr_cause VALUES (81, 'Invalid call reference value');
INSERT INTO cdr_cause VALUES (82, 'Identified channel does not exist');
INSERT INTO cdr_cause VALUES (83, 'A suspended call exists, but this call identity does not');
INSERT INTO cdr_cause VALUES (84, 'Call identity in use');
INSERT INTO cdr_cause VALUES (85, 'No call suspended');
INSERT INTO cdr_cause VALUES (86, 'Call having the requested call identity has been cleared');
INSERT INTO cdr_cause VALUES (87, 'User not member of CUG (Closed User Group)');
INSERT INTO cdr_cause VALUES (88, 'Incompatible destination');
INSERT INTO cdr_cause VALUES (90, 'Destination number missing and DC not subscribed');
INSERT INTO cdr_cause VALUES (91, 'Invalid transit network selection (national use)');
INSERT INTO cdr_cause VALUES (95, 'Invalid message, unspecified');
INSERT INTO cdr_cause VALUES (96, 'Mandatory information element is missing');
INSERT INTO cdr_cause VALUES (97, 'Message type nonexistent or not implemented');
INSERT INTO cdr_cause VALUES (98, 'Message is not compatible with the call state, or the message type is nonexistent or not implemented');
INSERT INTO cdr_cause VALUES (99, 'An information element or parameter does not exist or is not implemented');
INSERT INTO cdr_cause VALUES (100, 'Invalid information element contents');
INSERT INTO cdr_cause VALUES (101, 'The message is not compatible with the call state');
INSERT INTO cdr_cause VALUES (102, 'Call terminated when timer expired; a recovery routine executed to recover from the error');
INSERT INTO cdr_cause VALUES (103, 'Parameter nonexistent or not implemented - passed on (national use)');
INSERT INTO cdr_cause VALUES (110, 'Message with unrecognized parameter discarded');
INSERT INTO cdr_cause VALUES (111, 'Protocol error, unspecified');
INSERT INTO cdr_cause VALUES (122, 'Precedence Level Exceeded');
INSERT INTO cdr_cause VALUES (123, 'Device not Preemptable');
INSERT INTO cdr_cause VALUES (125, 'Out of bandwidth (Cisco specific)');
INSERT INTO cdr_cause VALUES (126, 'Call split (Cisco specific)');
INSERT INTO cdr_cause VALUES (127, 'Interworking, unspecified');
INSERT INTO cdr_cause VALUES (129, 'Precedence out of bandwidth');
INSERT INTO cdr_cause VALUES (131, 'Call Control Discovery PSTN Failover (Cisco specific)');
INSERT INTO cdr_cause VALUES (132, 'IME QOS Fallback (Cisco specific)');
INSERT INTO cdr_cause VALUES (133, 'PSTN Fallback locate Call Error (Cisco specific)');
INSERT INTO cdr_cause VALUES (134, 'PSTN Fallback wait for DTMF Timeout (Cisco specific)');
INSERT INTO cdr_cause VALUES (135, 'IME Failed Connection Timed out (Cisco specific)');
INSERT INTO cdr_cause VALUES (136, 'IME Failed not enrolled (Cisco specific)');
INSERT INTO cdr_cause VALUES (137, 'IME Failed socket error (Cisco specific)');
INSERT INTO cdr_cause VALUES (138, 'IME Failed domain blacklisted (Cisco specific)');
INSERT INTO cdr_cause VALUES (139, 'IME Failed prefix blacklisted (Cisco specific)');
INSERT INTO cdr_cause VALUES (140, 'IME Failed expired ticket (Cisco specific)');
INSERT INTO cdr_cause VALUES (141, 'IME Failed remote no matching route (Cisco specific)');
INSERT INTO cdr_cause VALUES (142, 'IME Failed remote unregistered (Cisco specific)');
INSERT INTO cdr_cause VALUES (143, 'IME Failed remote IME disabled (Cisco specific)');
INSERT INTO cdr_cause VALUES (144, 'IME Failed remote invalid IME trunk URI (Cisco specific)');
INSERT INTO cdr_cause VALUES (145, 'IME Failed remote URI not E164 (Cisco specific)');
INSERT INTO cdr_cause VALUES (146, 'IME Failed remote called number not available (Cisco specific)');
INSERT INTO cdr_cause VALUES (147, 'IME Failed Invalid Ticket (Cisco specific)');
INSERT INTO cdr_cause VALUES (148, 'IME Failed unknown (Cisco specific)');
INSERT INTO cdr_cause VALUES (262144, 'Conference Full');
INSERT INTO cdr_cause VALUES (393216, 'Call split');
INSERT INTO cdr_cause VALUES (458752, 'Conference drop any party/Conference drop last party');
INSERT INTO cdr_cause VALUES (16777257, 'CCM_SIP_400_BAD_REQUEST');
INSERT INTO cdr_cause VALUES (33554453, 'CCM_SIP_401_UNAUTHORIZED');
INSERT INTO cdr_cause VALUES (50331669, 'CCM_SIP_402_PAYMENT_REQUIRED');
INSERT INTO cdr_cause VALUES (67108885, 'CCM_SIP_403_FORBIDDEN');
INSERT INTO cdr_cause VALUES (83886081, 'CCM_SIP_404_NOT_FOUND');
INSERT INTO cdr_cause VALUES (100663359, 'CCM_SIP_405_METHOD_NOT_ALLOWED');
INSERT INTO cdr_cause VALUES (117440591, 'CCM_SIP_406_NOT_ACCEPTABLE');
INSERT INTO cdr_cause VALUES (134217749, 'CCM_SIP_407_PROXY_AUTHENTICATION_REQUIRED');
INSERT INTO cdr_cause VALUES (150995046, 'CCM_SIP_408_REQUEST_TIMEOUT');
INSERT INTO cdr_cause VALUES (184549398, 'CCM_SIP__410_GONE');
INSERT INTO cdr_cause VALUES (201326719, 'CCM_SIP_411_LENGTH_REQUIRED');
INSERT INTO cdr_cause VALUES (234881151, 'CCM_SIP_413_REQUEST_ENTITY_TOO_LONG');
INSERT INTO cdr_cause VALUES (251658367, 'CCM_SIP_414_REQUEST_URI_TOO_LONG');
INSERT INTO cdr_cause VALUES (268435535, 'CCM_SIP_415_UNSUPPORTED_MEDIA_TYPE');
INSERT INTO cdr_cause VALUES (285212799, 'CCM_SIP_416_UNSUPPORTED_URI_SCHEME');
INSERT INTO cdr_cause VALUES (83886207, 'CCM_SIP_420_BAD_EXTENSION');
INSERT INTO cdr_cause VALUES (369098879, 'CCM_SIP_421_EXTENSION_REQUIRED');
INSERT INTO cdr_cause VALUES (402653311, 'CCM_SIP_423_INTERVAL_TOO_BRIEF');
INSERT INTO cdr_cause VALUES (419430421, 'CCM_SIP_424_BAD_LOCATION_INFO');
INSERT INTO cdr_cause VALUES (1073741842, 'CCM_SIP_480_TEMPORARILY_UNAVAILABLE');
INSERT INTO cdr_cause VALUES (1090519081, 'CCM_SIP_481_CALL_LEG_DOES_NOT_EXIST');
INSERT INTO cdr_cause VALUES (1107296281, 'CCM_SIP_482_LOOP_DETECTED = 0x42000000 + EXCHANGE_ROUTING_ERROR');
INSERT INTO cdr_cause VALUES (1124073497, 'CCM_SIP_483_TOO_MANY_HOOPS');
INSERT INTO cdr_cause VALUES (1140850716, 'CCM_SIP_484_ADDRESS_INCOMPLETE');
INSERT INTO cdr_cause VALUES (1157627905, 'CCM_SIP_485_AMBIGUOUS');
INSERT INTO cdr_cause VALUES (1174405137, 'CCM_SIP_486_BUSY_HERE');
INSERT INTO cdr_cause VALUES (1191182367, 'CCM_SIP_487_REQUEST_TERMINATED');
INSERT INTO cdr_cause VALUES (1207959583, 'CCM_SIP_488_NOT_ACCEPTABLE_HERE');
INSERT INTO cdr_cause VALUES (1258291217, 'CCM_SIP_491_REQUEST_PENDING');
INSERT INTO cdr_cause VALUES (1291845649, 'CCM_SIP_493_UNDECIPHERABLE');
INSERT INTO cdr_cause VALUES (1409286185, 'CCM_SIP_500_SERVER_INTERNAL_ERROR');
INSERT INTO cdr_cause VALUES (1442840614, 'CCM_SIP_502_BAD_GATEWAY');
INSERT INTO cdr_cause VALUES (1459617833, 'CCM_SIP_503_SERVICE_UNAVAILABLE');
INSERT INTO cdr_cause VALUES (2801795135, 'CCM_SIP_503_SERVICE_UNAVAILABLE_SER_OPTION_NOAV');
INSERT INTO cdr_cause VALUES (1476395110, 'CCM_SIP__504_SERVER_TIME_OUT');
INSERT INTO cdr_cause VALUES (1493172351, 'CCM_SIP_505_SIP_VERSION_NOT_SUPPORTED');
INSERT INTO cdr_cause VALUES (1509949567, 'CCM_SIP_513_MESSAGE_TOO_LARGE');
INSERT INTO cdr_cause VALUES (2701131793, 'CCM_SIP_600_BUSY_EVERYWHERE');
INSERT INTO cdr_cause VALUES (2717909013, 'CCM_SIP_603_DECLINE');
INSERT INTO cdr_cause VALUES (2734686209, 'CCM_SIP_604_DOES_NOT_EXIST_ANYWHERE');
INSERT INTO cdr_cause VALUES (2751463455, 'CCM_SIP_606_NOT_ACCEPTABLE');


INSERT INTO cdr_codec VALUES (1, 'NonStandard');
INSERT INTO cdr_codec VALUES (2, 'G711Alaw 64k');
INSERT INTO cdr_codec VALUES (3, 'G711Alaw 56k');
INSERT INTO cdr_codec VALUES (4, 'G711mu-law 64k');
INSERT INTO cdr_codec VALUES (5, 'G711mu-law 56k');
INSERT INTO cdr_codec VALUES (6, 'G722 64k');
INSERT INTO cdr_codec VALUES (7, 'G722 56k');
INSERT INTO cdr_codec VALUES (8, 'G722 48k');
INSERT INTO cdr_codec VALUES (9, 'G7231');
INSERT INTO cdr_codec VALUES (10, 'G728');
INSERT INTO cdr_codec VALUES (11, 'G729');
INSERT INTO cdr_codec VALUES (12, 'G729AnnexA');
INSERT INTO cdr_codec VALUES (13, 'Is11172AudioCap');
INSERT INTO cdr_codec VALUES (14, 'Is13818AudioCap');
INSERT INTO cdr_codec VALUES (15, 'G.729AnnexB');
INSERT INTO cdr_codec VALUES (16, 'G.729 Annex AwAnnexB');
INSERT INTO cdr_codec VALUES (18, 'GSM Full Rate');
INSERT INTO cdr_codec VALUES (19, 'GSM Half Rate');
INSERT INTO cdr_codec VALUES (20, 'GSM Enhanced Full Rate');
INSERT INTO cdr_codec VALUES (25, 'Wideband 256K');
INSERT INTO cdr_codec VALUES (32, 'Data 64k');
INSERT INTO cdr_codec VALUES (33, 'Data 56k');
INSERT INTO cdr_codec VALUES (40, 'G7221 32K');
INSERT INTO cdr_codec VALUES (41, 'G7221 24K');
INSERT INTO cdr_codec VALUES (42, 'AAC');
INSERT INTO cdr_codec VALUES (43, 'MP4ALATM_NA');
INSERT INTO cdr_codec VALUES (44, 'MP4ALATM_64');
INSERT INTO cdr_codec VALUES (45, 'MP4ALATM_56');
INSERT INTO cdr_codec VALUES (46, 'MP4ALATM_128');
INSERT INTO cdr_codec VALUES (47, 'MP4ALATM_48');
INSERT INTO cdr_codec VALUES (48, 'MP4ALATM_32');
INSERT INTO cdr_codec VALUES (49, 'MP4ALATM_24');
INSERT INTO cdr_codec VALUES (80, 'GSM');
INSERT INTO cdr_codec VALUES (81, 'ActiveVoice');
INSERT INTO cdr_codec VALUES (82, 'G726 32K');
INSERT INTO cdr_codec VALUES (83, 'G726 24K');
INSERT INTO cdr_codec VALUES (84, 'G726 16K');
INSERT INTO cdr_codec VALUES (86, 'iLBC');
INSERT INTO cdr_codec VALUES (89, 'iSAC');
INSERT INTO cdr_codec VALUES (100, 'H261');
INSERT INTO cdr_codec VALUES (101, 'H263');
INSERT INTO cdr_codec VALUES (102, 'Vieo');
INSERT INTO cdr_codec VALUES (103, 'H264');
INSERT INTO cdr_codec VALUES (104, 'H264_SVC');
INSERT INTO cdr_codec VALUES (105, 'T120');
INSERT INTO cdr_codec VALUES (106, 'H224');
INSERT INTO cdr_codec VALUES (107, 'T38Fax');
INSERT INTO cdr_codec VALUES (108, 'TOTE');
INSERT INTO cdr_codec VALUES (109, 'H265');
INSERT INTO cdr_codec VALUES (110, 'H264_UC');
INSERT INTO cdr_codec VALUES (111, 'XV150_MR_711U');
INSERT INTO cdr_codec VALUES (112, 'NSE_VBD_711U');
INSERT INTO cdr_codec VALUES (113, 'XV150_MR_729A');
INSERT INTO cdr_codec VALUES (114, 'NSE_VBD_729A');
INSERT INTO cdr_codec VALUES (115, 'H264_FEC');
INSERT INTO cdr_codec VALUES (120, 'Clear_Chan');
INSERT INTO cdr_codec VALUES (222, 'Universal_Xcoder');
INSERT INTO cdr_codec VALUES (257, 'RFC2833_DynPayload');
INSERT INTO cdr_codec VALUES (258, 'PassThrough');
INSERT INTO cdr_codec VALUES (259, 'Dynamic_Payload_PassThru');
INSERT INTO cdr_codec VALUES (260, 'DTMF_OOB');
INSERT INTO cdr_codec VALUES (261, 'Inband_DTMF_RFC2833');
INSERT INTO cdr_codec VALUES (299, 'NoAudio');
INSERT INTO cdr_codec VALUES (300, 'v150_LC_ModemRelay');
INSERT INTO cdr_codec VALUES (301, 'v150_LC_SPRT');
INSERT INTO cdr_codec VALUES (302, 'v150_LC_SSE');


INSERT INTO cdr_onbehalfof VALUES (0, 'Unknown');
INSERT INTO cdr_onbehalfof VALUES (1, 'CctiLine');
INSERT INTO cdr_onbehalfof VALUES (2, 'Unicast Shared Resource Provider');
INSERT INTO cdr_onbehalfof VALUES (3, 'Call Park');
INSERT INTO cdr_onbehalfof VALUES (4, 'Conference');
INSERT INTO cdr_onbehalfof VALUES (5, 'Call Forward');
INSERT INTO cdr_onbehalfof VALUES (6, 'Meet-Me Conference');
INSERT INTO cdr_onbehalfof VALUES (7, 'Meet-Me Conference Intercepts');
INSERT INTO cdr_onbehalfof VALUES (8, 'Message Waiting');
INSERT INTO cdr_onbehalfof VALUES (9, 'Multicast Shared Resource Provider');
INSERT INTO cdr_onbehalfof VALUES (10, 'Transfer');
INSERT INTO cdr_onbehalfof VALUES (11, 'SSAPI Manager');
INSERT INTO cdr_onbehalfof VALUES (12, 'Device');
INSERT INTO cdr_onbehalfof VALUES (13, 'Call Control');
INSERT INTO cdr_onbehalfof VALUES (14, 'Immediate Divert');
INSERT INTO cdr_onbehalfof VALUES (15, 'Barge');
INSERT INTO cdr_onbehalfof VALUES (16, 'Pickup');
INSERT INTO cdr_onbehalfof VALUES (17, 'Refer');
INSERT INTO cdr_onbehalfof VALUES (18, 'Replaces');
INSERT INTO cdr_onbehalfof VALUES (19, 'Redirection');
INSERT INTO cdr_onbehalfof VALUES (20, 'Callback');
INSERT INTO cdr_onbehalfof VALUES (21, 'Path Replacement');
INSERT INTO cdr_onbehalfof VALUES (22, 'FacCmc Manager');
INSERT INTO cdr_onbehalfof VALUES (23, 'Malicious Call');
INSERT INTO cdr_onbehalfof VALUES (24, 'Mobility');
INSERT INTO cdr_onbehalfof VALUES (25, 'Aar');
INSERT INTO cdr_onbehalfof VALUES (26, 'Directed Call Park');
INSERT INTO cdr_onbehalfof VALUES (27, 'Recording');
INSERT INTO cdr_onbehalfof VALUES (28, 'Monitoring');
INSERT INTO cdr_onbehalfof VALUES (29, 'CCDRequestingService');
INSERT INTO cdr_onbehalfof VALUES (30, 'Intercompany Media Engine');
INSERT INTO cdr_onbehalfof VALUES (31, 'FallBack Manager');
INSERT INTO cdr_onbehalfof VALUES (32, 'Presence Enabled Routing');
INSERT INTO cdr_onbehalfof VALUES (33, 'AgentGreeting');
INSERT INTO cdr_onbehalfof VALUES (34, 'NativeCallQueuing');
INSERT INTO cdr_onbehalfof VALUES (35, 'MobileCallType');


INSERT INTO cdr_reason VALUES (0, 'Unknown');
INSERT INTO cdr_reason VALUES (1, 'Call Forward Busy');
INSERT INTO cdr_reason VALUES (2, 'Call Forward No Answer');
INSERT INTO cdr_reason VALUES (4, 'Call Transfer');
INSERT INTO cdr_reason VALUES (5, 'Call Pickup');
INSERT INTO cdr_reason VALUES (7, 'Call Park');
INSERT INTO cdr_reason VALUES (8, 'Call Park Pickup');
INSERT INTO cdr_reason VALUES (9, 'CPE Out of Order');
INSERT INTO cdr_reason VALUES (10, 'Call Forward');
INSERT INTO cdr_reason VALUES (11, 'Call Park Reversion');
INSERT INTO cdr_reason VALUES (15, 'Call Forward all');
INSERT INTO cdr_reason VALUES (18, 'Call Deflection');
INSERT INTO cdr_reason VALUES (34, 'Blind Transfer');
INSERT INTO cdr_reason VALUES (50, 'Call Immediate Divert');
INSERT INTO cdr_reason VALUES (66, 'Call Forward Alternate Party');
INSERT INTO cdr_reason VALUES (82, 'Call Forward On Failure');
INSERT INTO cdr_reason VALUES (98, 'Conference');
INSERT INTO cdr_reason VALUES (114, 'Barge');
INSERT INTO cdr_reason VALUES (129, 'Aar');
INSERT INTO cdr_reason VALUES (130, 'Refer');
INSERT INTO cdr_reason VALUES (146, 'Replaces');
INSERT INTO cdr_reason VALUES (162, 'Redirection (3xx)');
INSERT INTO cdr_reason VALUES (177, 'SIP-forward busy greeting');
INSERT INTO cdr_reason VALUES (178, 'Call Forward Unregistered');
INSERT INTO cdr_reason VALUES (207, 'Follow Me (SIP-forward all greeting)');
INSERT INTO cdr_reason VALUES (209, 'Out of Service (SIP-forward busy greeting)');
INSERT INTO cdr_reason VALUES (239, 'Time of Day (SIP-forward all greeting)');
INSERT INTO cdr_reason VALUES (242, 'Do Not Disturb (SIP-forward no answer greeting)');
INSERT INTO cdr_reason VALUES (257, 'Unavailable (SIP-forward busy greeting)');
INSERT INTO cdr_reason VALUES (274, 'Away (SIP-forward no answer greeting)');
INSERT INTO cdr_reason VALUES (303, 'Mobility HandIn');
INSERT INTO cdr_reason VALUES (319, 'Mobility HandOut');
INSERT INTO cdr_reason VALUES (335, 'Mobility Follow Me');
INSERT INTO cdr_reason VALUES (351, 'Mobility Redial');
INSERT INTO cdr_reason VALUES (354, 'Recording');
INSERT INTO cdr_reason VALUES (370, 'Monitoring');
INSERT INTO cdr_reason VALUES (399, 'Mobility IVR');
INSERT INTO cdr_reason VALUES (401, 'Mobility DVOR');
INSERT INTO cdr_reason VALUES (402, 'Mobility EFA');
INSERT INTO cdr_reason VALUES (403, 'Mobility Session Handoff');
INSERT INTO cdr_reason VALUES (415, 'Mobility Cell Pickup');
INSERT INTO cdr_reason VALUES (418, 'Click to Conference');
INSERT INTO cdr_reason VALUES (434, 'Forward No Retrieve');
INSERT INTO cdr_reason VALUES (450, 'Forward No Retrieve Send Back to Parker');
INSERT INTO cdr_reason VALUES (464, 'Call Control Discovery (indicates that the call is redirected to a PSTN failover number)');
INSERT INTO cdr_reason VALUES (480, 'Intercompany Media Engine (IME)');
INSERT INTO cdr_reason VALUES (496, 'IME Connection Timed Out');
INSERT INTO cdr_reason VALUES (512, 'IME Not Enrolled');
INSERT INTO cdr_reason VALUES (528, 'IME Socket Error');
INSERT INTO cdr_reason VALUES (544, 'IME Domain Blacklisted');
INSERT INTO cdr_reason VALUES (560, 'IME Prefix Blacklisted');
INSERT INTO cdr_reason VALUES (576, 'IME Expired Ticket');
INSERT INTO cdr_reason VALUES (592, 'IME Remote No Matching Route');
INSERT INTO cdr_reason VALUES (608, 'IME Remote Unregistered');
INSERT INTO cdr_reason VALUES (624, 'IME Remote IME Disabled');
INSERT INTO cdr_reason VALUES (640, 'IME Remote Invalid IME Trunk URI');
INSERT INTO cdr_reason VALUES (656, 'IME Remote URI not E164');
INSERT INTO cdr_reason VALUES (672, 'IME Remote Called Number Not Available');
INSERT INTO cdr_reason VALUES (688, 'IME Invalid Ticket');
INSERT INTO cdr_reason VALUES (704, 'IME Unknown');
INSERT INTO cdr_reason VALUES (720, 'IME PSTN Fallback');
INSERT INTO cdr_reason VALUES (738, 'Presence Enabled Routing');
INSERT INTO cdr_reason VALUES (752, 'Agent Greeting');
INSERT INTO cdr_reason VALUES (783, 'NuRD');
INSERT INTO cdr_reason VALUES (786, 'Native Call Queuing, queue a call');
INSERT INTO cdr_reason VALUES (802, 'Native Call Queuing, de-queue a call');
INSERT INTO cdr_reason VALUES (818, 'Native Call Queuing, redirect to the second destination when no agent is logged in');
INSERT INTO cdr_reason VALUES (834, 'Native Call Queuing, redirect to the second destination when the queue is full');
INSERT INTO cdr_reason VALUES (850, 'Native Call Queuing, redirect to the second destination when the maximum wait time in queue is reached');
